"""Local configuration for the shipped L2CS + torso runtime."""

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent

BODY_REGION_MODEL_PATH = str(BASE_DIR / "models" / "body_regions_yolov8s_seg.pt")
L2CS_WEIGHTS_PATH = str(BASE_DIR / "models" / "L2CSNet_gaze360.pkl")
L2CS_GDRIVE_FOLDER_URL = (
    "https://drive.google.com/drive/folders/"
    "17p6ORr-JQJcw-eYtG2WGNiuS_qVKwdWd?usp=sharing"
)

TARGET_LABEL = "upper_torso"
CONFIDENCE_THRESHOLD = 0.5

YOLO_IMAGE_SIZE = 640
YOLO_DEVICE = "auto"
DETECTION_GEOMETRY_SCALE = 1.10

L2CS_ARCH = "ResNet50"
L2CS_DEVICE = "auto"
L2CS_BASE_CONFIDENCE = 0.85
L2CS_RIDGE_LAMBDA = 0.08
L2CS_OUT_OF_RANGE_MARGIN = 0.12
L2CS_LOCAL_KNN_NEIGHBORS = 8
L2CS_LOCAL_KNN_OUT_OF_RANGE_MARGIN = 0.08
L2CS_GAZE_SMOOTHING_ALPHA = 0.36
L2CS_GAZE_MEDIAN_WINDOW = 3
L2CS_GAZE_MAX_STEP_PX = 420

CAMERA_INDEX = 0
SCREEN_CAPTURE_FPS = 8
SCREEN_MONITOR_INDEX = 1
SCREEN_WIDTH_FALLBACK = 1920
SCREEN_HEIGHT_FALLBACK = 1080

PREVIEW_MAX_WIDTH = 1280
PREVIEW_MAX_HEIGHT = 720
PREVIEW_WINDOW_NAME = "Live Gaze + YOLO Prototype - Phase 1"

GAZE_MIN_CONFIDENCE_FOR_HIT = 0.4
GAZE_HIT_RADIUS_PX = 250
GAZE_DWELL_MS = 150
GAZE_BLOB_RADIUS = 80
GAZE_BLOB_ALPHA = 0.35
GAZE_TRAIL_LENGTH = 18
NO_FACE_CENTER_FALLBACK = True
NO_FACE_FALLBACK_CONFIDENCE = 0.0
GAZE_MIN_SIGNAL_RANGE = 0.015

GAZE_CALIBRATION_MODEL = "auto"
GAZE_CALIBRATION_PROFILE = "dense5x5"
CALIBRATION_STANDARD_GRID_FRACTIONS = (0.15, 0.5, 0.85)
CALIBRATION_DENSE_GRID_FRACTIONS = (0.10, 0.30, 0.50, 0.70, 0.90)
CALIBRATION_DENSE_REFINEMENT_CORNERS = (
    (0.06, 0.06),
    (0.94, 0.06),
    (0.06, 0.94),
    (0.94, 0.94),
)
CALIBRATION_REFINEMENT_SAMPLE_SCALE = 0.65
L2CS_CALIBRATION_SAMPLE_SECONDS = 2.0
L2CS_CALIBRATION_VALIDATION_SECONDS = 2.0
L2CS_CALIBRATION_MIN_SAMPLES_PER_POINT = 6
L2CS_CALIBRATION_MAX_SAMPLE_SECONDS = 5.0
L2CS_CALIBRATION_WARMUP_SECONDS = 1.0
CALIBRATION_SETTLE_SECONDS = 0.9
CALIBRATION_GOOD_ERROR_PX = 250
CALIBRATION_POOR_ERROR_PX = 600

ALERT_ENABLED = False
ALERT_DURATION_MS = 2000
ALERT_COOLDOWN_SECONDS = 0.5
SCREEN_FLASH_ENABLED = False
SCREEN_FLASH_MODE = "overlay"  # overlay or white
SCREEN_FLASH_OVERLAY_ALPHA = 0.22
SCREEN_FLASH_OVERLAY_COLOR = "#ff3b30"
SCREEN_FLASH_WHITE_COLOR = "#ffffff"

METADATA_LOGGING_ENABLED = True
EVENT_LOG_PATH = str(BASE_DIR / "artifacts" / "events.jsonl")
EVENT_LOG_INTERVAL_SECONDS = 0.25
DIAGNOSTIC_LOGGING_ENABLED = True
DIAGNOSTIC_LOG_PATH = str(BASE_DIR / "artifacts" / "gaze_diagnostics.jsonl")
DIAGNOSTIC_LOG_INTERVAL_SECONDS = 0.5
CALIBRATION_DIAGNOSTICS_PATH = str(BASE_DIR / "artifacts" / "calibration_diagnostics.json")
CALIBRATION_PATH = str(BASE_DIR / "artifacts" / "calibration.json")
